/**
 * HIFDHI — Complete Surah Metadata (114 surahs)
 * 
 * Fields: id, ar (Arabic name), en (English name), v (verse count), 
 *         juz (primary juz), place (makkah/madinah), pages [start, end]
 */

const ALL_SURAHS = [
  { id: 1,   ar: "الفاتحة",     en: "Al-Fatiha",       v: 7,   juz: 1,  place: "makkah" },
  { id: 2,   ar: "البقرة",      en: "Al-Baqarah",      v: 286, juz: 1,  place: "madinah" },
  { id: 3,   ar: "آل عمران",    en: "Ali 'Imran",      v: 200, juz: 3,  place: "madinah" },
  { id: 4,   ar: "النساء",      en: "An-Nisa",         v: 176, juz: 4,  place: "madinah" },
  { id: 5,   ar: "المائدة",     en: "Al-Ma'idah",      v: 120, juz: 6,  place: "madinah" },
  { id: 6,   ar: "الأنعام",     en: "Al-An'am",        v: 165, juz: 7,  place: "makkah" },
  { id: 7,   ar: "الأعراف",     en: "Al-A'raf",        v: 206, juz: 8,  place: "makkah" },
  { id: 8,   ar: "الأنفال",     en: "Al-Anfal",        v: 75,  juz: 9,  place: "madinah" },
  { id: 9,   ar: "التوبة",      en: "At-Tawbah",       v: 129, juz: 10, place: "madinah" },
  { id: 10,  ar: "يونس",        en: "Yunus",           v: 109, juz: 11, place: "makkah" },
  { id: 11,  ar: "هود",         en: "Hud",             v: 123, juz: 11, place: "makkah" },
  { id: 12,  ar: "يوسف",        en: "Yusuf",           v: 111, juz: 12, place: "makkah" },
  { id: 13,  ar: "الرعد",       en: "Ar-Ra'd",         v: 43,  juz: 13, place: "madinah" },
  { id: 14,  ar: "إبراهيم",     en: "Ibrahim",         v: 52,  juz: 13, place: "makkah" },
  { id: 15,  ar: "الحجر",       en: "Al-Hijr",         v: 99,  juz: 14, place: "makkah" },
  { id: 16,  ar: "النحل",       en: "An-Nahl",         v: 128, juz: 14, place: "makkah" },
  { id: 17,  ar: "الإسراء",     en: "Al-Isra",         v: 111, juz: 15, place: "makkah" },
  { id: 18,  ar: "الكهف",       en: "Al-Kahf",         v: 110, juz: 15, place: "makkah" },
  { id: 19,  ar: "مريم",        en: "Maryam",          v: 98,  juz: 16, place: "makkah" },
  { id: 20,  ar: "طه",          en: "Ta-Ha",           v: 135, juz: 16, place: "makkah" },
  { id: 21,  ar: "الأنبياء",    en: "Al-Anbiya",       v: 112, juz: 17, place: "makkah" },
  { id: 22,  ar: "الحج",        en: "Al-Hajj",         v: 78,  juz: 17, place: "madinah" },
  { id: 23,  ar: "المؤمنون",    en: "Al-Mu'minun",     v: 118, juz: 18, place: "makkah" },
  { id: 24,  ar: "النور",       en: "An-Nur",          v: 64,  juz: 18, place: "madinah" },
  { id: 25,  ar: "الفرقان",     en: "Al-Furqan",       v: 77,  juz: 18, place: "makkah" },
  { id: 26,  ar: "الشعراء",     en: "Ash-Shu'ara",     v: 227, juz: 19, place: "makkah" },
  { id: 27,  ar: "النمل",       en: "An-Naml",         v: 93,  juz: 19, place: "makkah" },
  { id: 28,  ar: "القصص",       en: "Al-Qasas",        v: 88,  juz: 20, place: "makkah" },
  { id: 29,  ar: "العنكبوت",    en: "Al-'Ankabut",     v: 69,  juz: 20, place: "makkah" },
  { id: 30,  ar: "الروم",       en: "Ar-Rum",          v: 60,  juz: 21, place: "makkah" },
  { id: 31,  ar: "لقمان",       en: "Luqman",          v: 34,  juz: 21, place: "makkah" },
  { id: 32,  ar: "السجدة",      en: "As-Sajdah",       v: 30,  juz: 21, place: "makkah" },
  { id: 33,  ar: "الأحزاب",     en: "Al-Ahzab",        v: 73,  juz: 21, place: "madinah" },
  { id: 34,  ar: "سبأ",         en: "Saba",            v: 54,  juz: 22, place: "makkah" },
  { id: 35,  ar: "فاطر",        en: "Fatir",           v: 45,  juz: 22, place: "makkah" },
  { id: 36,  ar: "يس",          en: "Ya-Sin",          v: 83,  juz: 22, place: "makkah" },
  { id: 37,  ar: "الصافات",     en: "As-Saffat",       v: 182, juz: 23, place: "makkah" },
  { id: 38,  ar: "ص",           en: "Sad",             v: 88,  juz: 23, place: "makkah" },
  { id: 39,  ar: "الزمر",       en: "Az-Zumar",        v: 75,  juz: 23, place: "makkah" },
  { id: 40,  ar: "غافر",        en: "Ghafir",          v: 85,  juz: 24, place: "makkah" },
  { id: 41,  ar: "فصلت",        en: "Fussilat",        v: 54,  juz: 24, place: "makkah" },
  { id: 42,  ar: "الشورى",      en: "Ash-Shura",       v: 53,  juz: 25, place: "makkah" },
  { id: 43,  ar: "الزخرف",      en: "Az-Zukhruf",      v: 89,  juz: 25, place: "makkah" },
  { id: 44,  ar: "الدخان",      en: "Ad-Dukhan",       v: 59,  juz: 25, place: "makkah" },
  { id: 45,  ar: "الجاثية",     en: "Al-Jathiyah",     v: 37,  juz: 25, place: "makkah" },
  { id: 46,  ar: "الأحقاف",     en: "Al-Ahqaf",        v: 35,  juz: 26, place: "makkah" },
  { id: 47,  ar: "محمد",        en: "Muhammad",        v: 38,  juz: 26, place: "madinah" },
  { id: 48,  ar: "الفتح",       en: "Al-Fath",         v: 29,  juz: 26, place: "madinah" },
  { id: 49,  ar: "الحجرات",     en: "Al-Hujurat",      v: 18,  juz: 26, place: "madinah" },
  { id: 50,  ar: "ق",           en: "Qaf",             v: 45,  juz: 26, place: "makkah" },
  { id: 51,  ar: "الذاريات",    en: "Adh-Dhariyat",    v: 60,  juz: 26, place: "makkah" },
  { id: 52,  ar: "الطور",       en: "At-Tur",          v: 49,  juz: 27, place: "makkah" },
  { id: 53,  ar: "النجم",       en: "An-Najm",         v: 62,  juz: 27, place: "makkah" },
  { id: 54,  ar: "القمر",       en: "Al-Qamar",        v: 55,  juz: 27, place: "makkah" },
  { id: 55,  ar: "الرحمن",      en: "Ar-Rahman",       v: 78,  juz: 27, place: "madinah" },
  { id: 56,  ar: "الواقعة",     en: "Al-Waqi'ah",      v: 96,  juz: 27, place: "makkah" },
  { id: 57,  ar: "الحديد",      en: "Al-Hadid",        v: 29,  juz: 27, place: "madinah" },
  { id: 58,  ar: "المجادلة",    en: "Al-Mujadila",     v: 22,  juz: 28, place: "madinah" },
  { id: 59,  ar: "الحشر",       en: "Al-Hashr",        v: 24,  juz: 28, place: "madinah" },
  { id: 60,  ar: "الممتحنة",    en: "Al-Mumtahanah",   v: 13,  juz: 28, place: "madinah" },
  { id: 61,  ar: "الصف",        en: "As-Saff",         v: 14,  juz: 28, place: "madinah" },
  { id: 62,  ar: "الجمعة",      en: "Al-Jumu'ah",      v: 11,  juz: 28, place: "madinah" },
  { id: 63,  ar: "المنافقون",   en: "Al-Munafiqun",    v: 11,  juz: 28, place: "madinah" },
  { id: 64,  ar: "التغابن",     en: "At-Taghabun",     v: 18,  juz: 28, place: "madinah" },
  { id: 65,  ar: "الطلاق",      en: "At-Talaq",        v: 12,  juz: 28, place: "madinah" },
  { id: 66,  ar: "التحريم",     en: "At-Tahrim",       v: 12,  juz: 28, place: "madinah" },
  { id: 67,  ar: "الملك",       en: "Al-Mulk",         v: 30,  juz: 29, place: "makkah" },
  { id: 68,  ar: "القلم",       en: "Al-Qalam",        v: 52,  juz: 29, place: "makkah" },
  { id: 69,  ar: "الحاقة",      en: "Al-Haqqah",       v: 52,  juz: 29, place: "makkah" },
  { id: 70,  ar: "المعارج",     en: "Al-Ma'arij",      v: 44,  juz: 29, place: "makkah" },
  { id: 71,  ar: "نوح",         en: "Nuh",             v: 28,  juz: 29, place: "makkah" },
  { id: 72,  ar: "الجن",        en: "Al-Jinn",         v: 28,  juz: 29, place: "makkah" },
  { id: 73,  ar: "المزمل",      en: "Al-Muzzammil",    v: 20,  juz: 29, place: "makkah" },
  { id: 74,  ar: "المدثر",      en: "Al-Muddaththir",  v: 56,  juz: 29, place: "makkah" },
  { id: 75,  ar: "القيامة",     en: "Al-Qiyamah",      v: 40,  juz: 29, place: "makkah" },
  { id: 76,  ar: "الإنسان",     en: "Al-Insan",        v: 31,  juz: 29, place: "madinah" },
  { id: 77,  ar: "المرسلات",    en: "Al-Mursalat",     v: 50,  juz: 29, place: "makkah" },
  { id: 78,  ar: "النبأ",       en: "An-Naba",         v: 40,  juz: 30, place: "makkah" },
  { id: 79,  ar: "النازعات",    en: "An-Nazi'at",      v: 46,  juz: 30, place: "makkah" },
  { id: 80,  ar: "عبس",         en: "'Abasa",          v: 42,  juz: 30, place: "makkah" },
  { id: 81,  ar: "التكوير",     en: "At-Takwir",       v: 29,  juz: 30, place: "makkah" },
  { id: 82,  ar: "الانفطار",    en: "Al-Infitar",      v: 19,  juz: 30, place: "makkah" },
  { id: 83,  ar: "المطففين",    en: "Al-Mutaffifin",   v: 36,  juz: 30, place: "makkah" },
  { id: 84,  ar: "الانشقاق",    en: "Al-Inshiqaq",     v: 25,  juz: 30, place: "makkah" },
  { id: 85,  ar: "البروج",      en: "Al-Buruj",        v: 22,  juz: 30, place: "makkah" },
  { id: 86,  ar: "الطارق",      en: "At-Tariq",        v: 17,  juz: 30, place: "makkah" },
  { id: 87,  ar: "الأعلى",      en: "Al-A'la",         v: 19,  juz: 30, place: "makkah" },
  { id: 88,  ar: "الغاشية",     en: "Al-Ghashiyah",    v: 26,  juz: 30, place: "makkah" },
  { id: 89,  ar: "الفجر",       en: "Al-Fajr",         v: 30,  juz: 30, place: "makkah" },
  { id: 90,  ar: "البلد",       en: "Al-Balad",        v: 20,  juz: 30, place: "makkah" },
  { id: 91,  ar: "الشمس",       en: "Ash-Shams",       v: 15,  juz: 30, place: "makkah" },
  { id: 92,  ar: "الليل",       en: "Al-Layl",         v: 21,  juz: 30, place: "makkah" },
  { id: 93,  ar: "الضحى",       en: "Ad-Duhaa",        v: 11,  juz: 30, place: "makkah" },
  { id: 94,  ar: "الشرح",       en: "Ash-Sharh",       v: 8,   juz: 30, place: "makkah" },
  { id: 95,  ar: "التين",       en: "At-Tin",          v: 8,   juz: 30, place: "makkah" },
  { id: 96,  ar: "العلق",       en: "Al-'Alaq",        v: 19,  juz: 30, place: "makkah" },
  { id: 97,  ar: "القدر",       en: "Al-Qadr",         v: 5,   juz: 30, place: "makkah" },
  { id: 98,  ar: "البينة",      en: "Al-Bayyinah",     v: 8,   juz: 30, place: "madinah" },
  { id: 99,  ar: "الزلزلة",     en: "Az-Zalzalah",     v: 8,   juz: 30, place: "madinah" },
  { id: 100, ar: "العاديات",    en: "Al-'Adiyat",      v: 11,  juz: 30, place: "makkah" },
  { id: 101, ar: "القارعة",     en: "Al-Qari'ah",      v: 11,  juz: 30, place: "makkah" },
  { id: 102, ar: "التكاثر",     en: "At-Takathur",     v: 8,   juz: 30, place: "makkah" },
  { id: 103, ar: "العصر",       en: "Al-'Asr",         v: 3,   juz: 30, place: "makkah" },
  { id: 104, ar: "الهمزة",      en: "Al-Humazah",      v: 9,   juz: 30, place: "makkah" },
  { id: 105, ar: "الفيل",       en: "Al-Fil",          v: 5,   juz: 30, place: "makkah" },
  { id: 106, ar: "قريش",        en: "Quraysh",         v: 4,   juz: 30, place: "makkah" },
  { id: 107, ar: "الماعون",     en: "Al-Ma'un",        v: 7,   juz: 30, place: "makkah" },
  { id: 108, ar: "الكوثر",      en: "Al-Kawthar",      v: 3,   juz: 30, place: "makkah" },
  { id: 109, ar: "الكافرون",    en: "Al-Kafirun",      v: 6,   juz: 30, place: "makkah" },
  { id: 110, ar: "النصر",       en: "An-Nasr",         v: 3,   juz: 30, place: "madinah" },
  { id: 111, ar: "المسد",       en: "Al-Masad",        v: 5,   juz: 30, place: "makkah" },
  { id: 112, ar: "الإخلاص",     en: "Al-Ikhlas",       v: 4,   juz: 30, place: "makkah" },
  { id: 113, ar: "الفلق",       en: "Al-Falaq",        v: 5,   juz: 30, place: "makkah" },
  { id: 114, ar: "الناس",       en: "An-Nas",          v: 6,   juz: 30, place: "makkah" },
];

export default ALL_SURAHS;
